//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ProductionOrder = new HashSet<ProductionOrder>();
        }
    
        public int ClientId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductionOrder> ProductionOrder { get; set; }
    }
}
