//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.StageAssignment = new HashSet<StageAssignment>();
            this.WorkLog = new HashSet<WorkLog>();
        }
    
        public int EmployeeId { get; set; }
        public string PersonnelNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string Qualifications { get; set; }
        public string RateType { get; set; }
        public decimal RateValue { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<StageAssignment> StageAssignment { get; set; }
        public virtual ICollection<WorkLog> WorkLog { get; set; }
    }
}
