//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.EquipmentUsageLog = new HashSet<EquipmentUsageLog>();
            this.StageAssignment = new HashSet<StageAssignment>();
        }
    
        public int EquipmentId { get; set; }
        public string InventoryNo { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public System.DateTime Commissioned { get; set; }
        public string Status { get; set; }
        public string MaintenancePlan { get; set; }
    
        public virtual ICollection<EquipmentUsageLog> EquipmentUsageLog { get; set; }
        public virtual ICollection<StageAssignment> StageAssignment { get; set; }
    }
}
