//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.PurchaseOrderItem = new HashSet<PurchaseOrderItem>();
            this.PurchaseReceiptItem = new HashSet<PurchaseReceiptItem>();
            this.StockBalance = new HashSet<StockBalance>();
            this.SupplierMaterialTerms = new HashSet<SupplierMaterialTerms>();
        }
    
        public int MaterialId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public decimal MinQty { get; set; }
        public decimal MarketPrice { get; set; }
    
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItem { get; set; }
        public virtual ICollection<PurchaseReceiptItem> PurchaseReceiptItem { get; set; }
        public virtual ICollection<StockBalance> StockBalance { get; set; }
        public virtual ICollection<SupplierMaterialTerms> SupplierMaterialTerms { get; set; }
    }
}
