//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class intergrirovanieEntities : DbContext
    {
        public intergrirovanieEntities()
            : base("name=intergrirovanieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillOfMaterials> BillOfMaterials { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EquipmentUsageLog> EquipmentUsageLog { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductionOrder> ProductionOrder { get; set; }
        public DbSet<ProductionStage> ProductionStage { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrder { get; set; }
        public DbSet<PurchaseOrderItem> PurchaseOrderItem { get; set; }
        public DbSet<PurchaseReceipt> PurchaseReceipt { get; set; }
        public DbSet<PurchaseReceiptItem> PurchaseReceiptItem { get; set; }
        public DbSet<QualityDefect> QualityDefect { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<StageAssignment> StageAssignment { get; set; }
        public DbSet<StockBalance> StockBalance { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<SupplierMaterialTerms> SupplierMaterialTerms { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TechOperation> TechOperation { get; set; }
        public DbSet<TechRoute> TechRoute { get; set; }
        public DbSet<UserRole> UserRole { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Warehouse> Warehouse { get; set; }
        public DbSet<WorkLog> WorkLog { get; set; }
    }
}
