//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.BillOfMaterials = new HashSet<BillOfMaterials>();
            this.ProductionOrder = new HashSet<ProductionOrder>();
            this.TechRoute = new HashSet<TechRoute>();
        }
    
        public int ProductId { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual ICollection<ProductionOrder> ProductionOrder { get; set; }
        public virtual ICollection<TechRoute> TechRoute { get; set; }
    }
}
