//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        public ProductionOrder()
        {
            this.ProductionStage = new HashSet<ProductionStage>();
        }
    
        public int ProductionOrderId { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public decimal Qty { get; set; }
        public string Priority { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductionStage> ProductionStage { get; set; }
    }
}
