//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStage
    {
        public ProductionStage()
        {
            this.EquipmentUsageLog = new HashSet<EquipmentUsageLog>();
            this.QualityDefect = new HashSet<QualityDefect>();
            this.StageAssignment = new HashSet<StageAssignment>();
            this.WorkLog = new HashSet<WorkLog>();
        }
    
        public int ProductionStageId { get; set; }
        public int ProductionOrderId { get; set; }
        public int SeqNo { get; set; }
        public string StageType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual ICollection<EquipmentUsageLog> EquipmentUsageLog { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual ICollection<QualityDefect> QualityDefect { get; set; }
        public virtual ICollection<StageAssignment> StageAssignment { get; set; }
        public virtual ICollection<WorkLog> WorkLog { get; set; }
    }
}
