//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipt
    {
        public PurchaseReceipt()
        {
            this.PurchaseReceiptItem = new HashSet<PurchaseReceiptItem>();
        }
    
        public int PurchaseReceiptId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int WarehouseId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string Status { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<PurchaseReceiptItem> PurchaseReceiptItem { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
