//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceiptItem
    {
        public int PurchaseReceiptItemId { get; set; }
        public int PurchaseReceiptId { get; set; }
        public int MaterialId { get; set; }
        public decimal QtyAccepted { get; set; }
        public decimal QtyRejected { get; set; }
        public string RejectReason { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual PurchaseReceipt PurchaseReceipt { get; set; }
    }
}
