//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.PurchaseOrderItem = new HashSet<PurchaseOrderItem>();
            this.PurchaseReceipt = new HashSet<PurchaseReceipt>();
        }
    
        public int PurchaseOrderId { get; set; }
        public int SupplierId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItem { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PurchaseReceipt> PurchaseReceipt { get; set; }
    }
}
