//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityDefect
    {
        public int QualityDefectId { get; set; }
        public int ProductionStageId { get; set; }
        public string Description { get; set; }
        public string Severity { get; set; }
        public string Decision { get; set; }
        public Nullable<decimal> QtyAffected { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
