//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaterialTerms
    {
        public int SupplierMaterialTermsId { get; set; }
        public int SupplierId { get; set; }
        public int MaterialId { get; set; }
        public int LeadTimeDays { get; set; }
        public decimal MinBatchQty { get; set; }
        public decimal DiscountPct { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
