//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.SupplierMaterialTerms = new HashSet<SupplierMaterialTerms>();
        }
    
        public int SupplierId { get; set; }
        public string Inn { get; set; }
        public string Name { get; set; }
        public string Contacts { get; set; }
        public Nullable<byte> Rating { get; set; }
        public string PayTerms { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        public virtual ICollection<SupplierMaterialTerms> SupplierMaterialTerms { get; set; }
    }
}
