//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechOperation
    {
        public int TechOperationId { get; set; }
        public int TechRouteId { get; set; }
        public int SeqNo { get; set; }
        public string Name { get; set; }
        public string StageType { get; set; }
        public int NormMinutes { get; set; }
    
        public virtual TechRoute TechRoute { get; set; }
    }
}
