//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechRoute
    {
        public TechRoute()
        {
            this.TechOperation = new HashSet<TechOperation>();
        }
    
        public int TechRouteId { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<TechOperation> TechOperation { get; set; }
    }
}
