//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.PurchaseReceipt = new HashSet<PurchaseReceipt>();
            this.StockBalance = new HashSet<StockBalance>();
        }
    
        public int WarehouseId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<PurchaseReceipt> PurchaseReceipt { get; set; }
        public virtual ICollection<StockBalance> StockBalance { get; set; }
    }
}
