//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLog
    {
        public int WorkLogId { get; set; }
        public int ProductionStageId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public decimal Hours { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
